/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */

import io.ktor.server.testing.*
import org.jetbrains.exposed.sql.Database
import xyz.daimones.ktor.admin.Admin
import xyz.daimones.ktor.admin.Configuration
import xyz.daimones.ktor.admin.ModelView
import kotlin.test.Test
import kotlin.test.assertEquals

class LibraryTest {
    @Test
    fun testAdminClass() = testApplication {
        application {
            val database = Database.connect(
                "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1",
                driver = "org.h2.Driver"
            )
            val configuration = Configuration(setAuthentication = false)
            val admin = Admin(this, database, configuration)
            admin.addView(ModelView())
            assertEquals(1, admin.countModelViews(), "Admin should have one model view registered")
        }

    }
}
